# https://taskfile.dev

version: "3"

interval: 500ms

tasks:
  runc:
    desc: Build an run NSQLite CLI
    deps: [buildc]
    cmd: ./dist/nsqlite {{.CLI_ARGS}}

  buildc:
    desc: Build NSQLite CLI
    cmd: go build -o ./dist/nsqlite ./cmd/nsqlite/.

  devs:
    desc: Build and serve NSQLite Server with hot reload
    watch: true
    deps: [builds]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  runs:
    desc: Build and run NSQLite Server
    deps: [builds]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  builds:
    desc: Build NSQLite Server
    sources:
      - "**/*.go"
      - exclude: ./.git/**
      - exclude: ./temp/**
      - exclude: ./tmp/**
      - exclude: ./dist/**
      - exclude: "**/*_test.go"
    generates:
      - ./dist/nsqlited
    cmd: go build -o ./dist/nsqlited ./cmd/nsqlited/.

  test:
    desc: Run tests
    cmd: go test ./...
