# https://taskfile.dev

version: "3"

interval: 500ms

tasks:
  install:
    desc: Build and install binaries in local system using go install
    cmds:
      - go install ./cmd/nsqlite/.
      - go install ./cmd/nsqlited/.
      - go install ./cmd/nsqlitebench/.

  runc:
    desc: Build an run NSQLite CLI
    deps: [buildc]
    cmd: ./dist/nsqlite {{.CLI_ARGS}}

  buildc:
    desc: Build NSQLite CLI
    sources:
      - "**/*.go"
      - exclude: ./internal/nsqlited/**/*
      - exclude: ./internal/nsqlitebench/**/*
      - exclude: ./.git/**/*
      - exclude: ./temp/**/*
      - exclude: ./tmp/**/*
      - exclude: ./dist/**/*
      - exclude: "**/*_test.go"
    generates:
      - ./dist/nsqlite
    cmd: go build -o ./dist/nsqlite ./cmd/nsqlite/.

  devs:
    desc: Build and serve NSQLite Server with hot reload
    watch: true
    deps: [builds]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  runs:
    desc: Build and run NSQLite Server
    deps: [builds]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  builds:
    desc: Build NSQLite Server
    sources:
      - "**/*.go"
      - exclude: ./internal/nsqlite/**/*
      - exclude: ./internal/nsqlitebench/**/*
      - exclude: ./.git/**/*
      - exclude: ./temp/**/*
      - exclude: ./tmp/**/*
      - exclude: ./dist/**/*
      - exclude: "**/*_test.go"
    generates:
      - ./dist/nsqlited
    cmd: go build -o ./dist/nsqlited ./cmd/nsqlited/.

  runb:
    desc: Build an run NSQLite Benchmark
    deps: [buildb]
    cmd: ./dist/nsqlitebench {{.CLI_ARGS}}

  buildb:
    desc: Build NSQLite Benchmark
    sources:
      - "**/*.go"
      - exclude: ./internal/nsqlite/**/*
      - exclude: ./internal/nsqlited/**/*
      - exclude: ./.git/**/*
      - exclude: ./temp/**/*
      - exclude: ./tmp/**/*
      - exclude: ./dist/**/*
      - exclude: "**/*_test.go"
    generates:
      - ./dist/nsqlitebench
    cmd: go build -o ./dist/nsqlitebench ./cmd/nsqlitebench/.

  lint:
    desc: Run linter
    cmds: golangci-lint run ./...

  test:
    desc: Run tests
    cmd: go test ./...
