# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build the binaries for all platforms
    cmd: chmod +x ./build.ts && ./build.ts

  install:
    desc: Build and install binaries in local system using go install
    cmds:
      - go install ./cmd/nsqlite/.
      - go install ./cmd/nsqlited/.

  runc:
    desc: Build an run NSQLite CLI
    deps: [buildc]
    cmd: ./dist/nsqlite {{.CLI_ARGS}}

  buildc:
    desc: Build NSQLite CLI
    cmd: go build -o ./dist/nsqlite ./cmd/nsqlite/.

  runs:
    desc: Build and run NSQLite Server
    deps: [builds]
    cmd: ./dist/nsqlited {{.CLI_ARGS}}

  builds:
    desc: Build NSQLite Server
    cmd: go build -o ./dist/nsqlited ./cmd/nsqlited/.

  lint:
    desc: Run linter
    cmd: golangci-lint run ./...

  test:
    desc: Run tests
    cmd: go test ./...
