package sqlitec

/*
#cgo LDFLAGS: -Wl,--allow-multiple-definition
#include "sqlite3.c"
*/
import "C"
import "fmt"

// getResCodeStr returns the string representation of the SQLite result code.
func getResCodeStr(resCode C.int) string {
	return fmt.Sprintf("%v: %s", resCode, C.GoString(C.sqlite3_errstr(resCode)))
}

// Primary Result Code List
//   - https://www.sqlite.org/rescode.html
//   - https://www.sqlite.org/c3ref/c_abort.html
const (
	SQLITE_OK         = C.SQLITE_OK
	SQLITE_ERROR      = C.SQLITE_ERROR
	SQLITE_INTERNAL   = C.SQLITE_INTERNAL
	SQLITE_PERM       = C.SQLITE_PERM
	SQLITE_ABORT      = C.SQLITE_ABORT
	SQLITE_BUSY       = C.SQLITE_BUSY
	SQLITE_LOCKED     = C.SQLITE_LOCKED
	SQLITE_NOMEM      = C.SQLITE_NOMEM
	SQLITE_READONLY   = C.SQLITE_READONLY
	SQLITE_INTERRUPT  = C.SQLITE_INTERRUPT
	SQLITE_IOERR      = C.SQLITE_IOERR
	SQLITE_CORRUPT    = C.SQLITE_CORRUPT
	SQLITE_NOTFOUND   = C.SQLITE_NOTFOUND
	SQLITE_FULL       = C.SQLITE_FULL
	SQLITE_CANTOPEN   = C.SQLITE_CANTOPEN
	SQLITE_PROTOCOL   = C.SQLITE_PROTOCOL
	SQLITE_EMPTY      = C.SQLITE_EMPTY
	SQLITE_SCHEMA     = C.SQLITE_SCHEMA
	SQLITE_TOOBIG     = C.SQLITE_TOOBIG
	SQLITE_CONSTRAINT = C.SQLITE_CONSTRAINT
	SQLITE_MISMATCH   = C.SQLITE_MISMATCH
	SQLITE_MISUSE     = C.SQLITE_MISUSE
	SQLITE_NOLFS      = C.SQLITE_NOLFS
	SQLITE_AUTH       = C.SQLITE_AUTH
	SQLITE_FORMAT     = C.SQLITE_FORMAT
	SQLITE_RANGE      = C.SQLITE_RANGE
	SQLITE_NOTADB     = C.SQLITE_NOTADB
	SQLITE_NOTICE     = C.SQLITE_NOTICE
	SQLITE_WARNING    = C.SQLITE_WARNING
	SQLITE_ROW        = C.SQLITE_ROW
	SQLITE_DONE       = C.SQLITE_DONE
)

// Extended Result Code List
//   - https://www.sqlite.org/rescode.html
//   - https://www.sqlite.org/c3ref/c_abort_rollback.html
const (
	SQLITE_ERROR_MISSING_COLLSEQ   = C.SQLITE_ERROR_MISSING_COLLSEQ
	SQLITE_ERROR_RETRY             = C.SQLITE_ERROR_RETRY
	SQLITE_ERROR_SNAPSHOT          = C.SQLITE_ERROR_SNAPSHOT
	SQLITE_IOERR_READ              = C.SQLITE_IOERR_READ
	SQLITE_IOERR_SHORT_READ        = C.SQLITE_IOERR_SHORT_READ
	SQLITE_IOERR_WRITE             = C.SQLITE_IOERR_WRITE
	SQLITE_IOERR_FSYNC             = C.SQLITE_IOERR_FSYNC
	SQLITE_IOERR_DIR_FSYNC         = C.SQLITE_IOERR_DIR_FSYNC
	SQLITE_IOERR_TRUNCATE          = C.SQLITE_IOERR_TRUNCATE
	SQLITE_IOERR_FSTAT             = C.SQLITE_IOERR_FSTAT
	SQLITE_IOERR_UNLOCK            = C.SQLITE_IOERR_UNLOCK
	SQLITE_IOERR_RDLOCK            = C.SQLITE_IOERR_RDLOCK
	SQLITE_IOERR_DELETE            = C.SQLITE_IOERR_DELETE
	SQLITE_IOERR_BLOCKED           = C.SQLITE_IOERR_BLOCKED
	SQLITE_IOERR_NOMEM             = C.SQLITE_IOERR_NOMEM
	SQLITE_IOERR_ACCESS            = C.SQLITE_IOERR_ACCESS
	SQLITE_IOERR_CHECKRESERVEDLOCK = C.SQLITE_IOERR_CHECKRESERVEDLOCK
	SQLITE_IOERR_LOCK              = C.SQLITE_IOERR_LOCK
	SQLITE_IOERR_CLOSE             = C.SQLITE_IOERR_CLOSE
	SQLITE_IOERR_DIR_CLOSE         = C.SQLITE_IOERR_DIR_CLOSE
	SQLITE_IOERR_SHMOPEN           = C.SQLITE_IOERR_SHMOPEN
	SQLITE_IOERR_SHMSIZE           = C.SQLITE_IOERR_SHMSIZE
	SQLITE_IOERR_SHMLOCK           = C.SQLITE_IOERR_SHMLOCK
	SQLITE_IOERR_SHMMAP            = C.SQLITE_IOERR_SHMMAP
	SQLITE_IOERR_SEEK              = C.SQLITE_IOERR_SEEK
	SQLITE_IOERR_DELETE_NOENT      = C.SQLITE_IOERR_DELETE_NOENT
	SQLITE_IOERR_MMAP              = C.SQLITE_IOERR_MMAP
	SQLITE_IOERR_GETTEMPPATH       = C.SQLITE_IOERR_GETTEMPPATH
	SQLITE_IOERR_CONVPATH          = C.SQLITE_IOERR_CONVPATH
	SQLITE_IOERR_VNODE             = C.SQLITE_IOERR_VNODE
	SQLITE_IOERR_AUTH              = C.SQLITE_IOERR_AUTH
	SQLITE_IOERR_BEGIN_ATOMIC      = C.SQLITE_IOERR_BEGIN_ATOMIC
	SQLITE_IOERR_COMMIT_ATOMIC     = C.SQLITE_IOERR_COMMIT_ATOMIC
	SQLITE_IOERR_ROLLBACK_ATOMIC   = C.SQLITE_IOERR_ROLLBACK_ATOMIC
	SQLITE_IOERR_DATA              = C.SQLITE_IOERR_DATA
	SQLITE_IOERR_CORRUPTFS         = C.SQLITE_IOERR_CORRUPTFS
	SQLITE_IOERR_IN_PAGE           = C.SQLITE_IOERR_IN_PAGE
	SQLITE_LOCKED_SHAREDCACHE      = C.SQLITE_LOCKED_SHAREDCACHE
	SQLITE_LOCKED_VTAB             = C.SQLITE_LOCKED_VTAB
	SQLITE_BUSY_RECOVERY           = C.SQLITE_BUSY_RECOVERY
	SQLITE_BUSY_SNAPSHOT           = C.SQLITE_BUSY_SNAPSHOT
	SQLITE_BUSY_TIMEOUT            = C.SQLITE_BUSY_TIMEOUT
	SQLITE_CANTOPEN_NOTEMPDIR      = C.SQLITE_CANTOPEN_NOTEMPDIR
	SQLITE_CANTOPEN_ISDIR          = C.SQLITE_CANTOPEN_ISDIR
	SQLITE_CANTOPEN_FULLPATH       = C.SQLITE_CANTOPEN_FULLPATH
	SQLITE_CANTOPEN_CONVPATH       = C.SQLITE_CANTOPEN_CONVPATH
	SQLITE_CANTOPEN_DIRTYWAL       = C.SQLITE_CANTOPEN_DIRTYWAL
	SQLITE_CANTOPEN_SYMLINK        = C.SQLITE_CANTOPEN_SYMLINK
	SQLITE_CORRUPT_VTAB            = C.SQLITE_CORRUPT_VTAB
	SQLITE_CORRUPT_SEQUENCE        = C.SQLITE_CORRUPT_SEQUENCE
	SQLITE_CORRUPT_INDEX           = C.SQLITE_CORRUPT_INDEX
	SQLITE_READONLY_RECOVERY       = C.SQLITE_READONLY_RECOVERY
	SQLITE_READONLY_CANTLOCK       = C.SQLITE_READONLY_CANTLOCK
	SQLITE_READONLY_ROLLBACK       = C.SQLITE_READONLY_ROLLBACK
	SQLITE_READONLY_DBMOVED        = C.SQLITE_READONLY_DBMOVED
	SQLITE_READONLY_CANTINIT       = C.SQLITE_READONLY_CANTINIT
	SQLITE_READONLY_DIRECTORY      = C.SQLITE_READONLY_DIRECTORY
	SQLITE_ABORT_ROLLBACK          = C.SQLITE_ABORT_ROLLBACK
	SQLITE_CONSTRAINT_CHECK        = C.SQLITE_CONSTRAINT_CHECK
	SQLITE_CONSTRAINT_COMMITHOOK   = C.SQLITE_CONSTRAINT_COMMITHOOK
	SQLITE_CONSTRAINT_FOREIGNKEY   = C.SQLITE_CONSTRAINT_FOREIGNKEY
	SQLITE_CONSTRAINT_FUNCTION     = C.SQLITE_CONSTRAINT_FUNCTION
	SQLITE_CONSTRAINT_NOTNULL      = C.SQLITE_CONSTRAINT_NOTNULL
	SQLITE_CONSTRAINT_PRIMARYKEY   = C.SQLITE_CONSTRAINT_PRIMARYKEY
	SQLITE_CONSTRAINT_TRIGGER      = C.SQLITE_CONSTRAINT_TRIGGER
	SQLITE_CONSTRAINT_UNIQUE       = C.SQLITE_CONSTRAINT_UNIQUE
	SQLITE_CONSTRAINT_VTAB         = C.SQLITE_CONSTRAINT_VTAB
	SQLITE_CONSTRAINT_ROWID        = C.SQLITE_CONSTRAINT_ROWID
	SQLITE_CONSTRAINT_PINNED       = C.SQLITE_CONSTRAINT_PINNED
	SQLITE_CONSTRAINT_DATATYPE     = C.SQLITE_CONSTRAINT_DATATYPE
	SQLITE_NOTICE_RECOVER_WAL      = C.SQLITE_NOTICE_RECOVER_WAL
	SQLITE_NOTICE_RECOVER_ROLLBACK = C.SQLITE_NOTICE_RECOVER_ROLLBACK
	SQLITE_NOTICE_RBU              = C.SQLITE_NOTICE_RBU
	SQLITE_WARNING_AUTOINDEX       = C.SQLITE_WARNING_AUTOINDEX
	SQLITE_AUTH_USER               = C.SQLITE_AUTH_USER
	SQLITE_OK_LOAD_PERMANENTLY     = C.SQLITE_OK_LOAD_PERMANENTLY
	SQLITE_OK_SYMLINK              = C.SQLITE_OK_SYMLINK
)
