name: Build and Attach Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-attach:
    name: Lint, Test, Build and Attach Assets to Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .ssh directory exists even if it's empty
        run: mkdir -p /home/runner/.ssh

      - name: Lint, Test and Build using Dev Containers
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: task lint && task test && task build

      - name: Upload linux-amd64.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/linux-amd64.zip
          asset_name: linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload linux-arm64.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/linux-arm64.zip
          asset_name: linux-arm64.zip
          asset_content_type: application/zip

      - name: Upload windows-amd64.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/windows-amd64.zip
          asset_name: windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload windows-arm64.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/windows-arm64.zip
          asset_name: windows-arm64.zip
          asset_content_type: application/zip
