name: Lint and Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and test the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lint, test and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: task lint && task test && task build
