name: Lint, test and build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint, test and build the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .ssh directory exists even if it's empty
        run: mkdir -p /home/runner/.ssh

      - name: Run lint, test and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: task lint && task test && task build
